// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.API.Contexts;

#nullable disable

namespace Pokedex.API.Migrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20260130191218_IntiaMigrationl")]
    partial class IntiaMigrationl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Pokedex.API.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "bulba boy",
                            Name = "Bulbasaur",
                            Type1 = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 2,
                            Description = "big bulba",
                            Name = "Ivysaur",
                            Type1 = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 3,
                            Description = "bulba chungus",
                            Name = "Venusaur",
                            Type1 = "grass",
                            Type2 = "poison"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
